
config_setting(
	name = "ios_sim_arm64",
	values = {"cpu": "ios_sim_arm64"},
)

config_setting(
	name = "ios_sim_x86_64",
	values = {"cpu": "ios_x86_64"},
)

config_setting(
	name = "ios_x86_64",
	values = {"cpu": "ios_x86_64"},
)

exports_files([
    "GenerateStrings/GenerateStrings.py",
])
